const romanceCovers = [
  { title: "It Ends With Us", author: "Colleen Hoover", image: { url: "https://covers.openlibrary.org/b/id/10308498-L.jpg" } },
  { title: "It Starts With Us", author: "Colleen Hoover", image: { url: "https://covers.openlibrary.org/b/id/13257523-L.jpg" } },
  { title: "Verity", author: "Colleen Hoover", image: { url: "https://covers.openlibrary.org/b/id/12992070-L.jpg" } },
  { title: "Ugly Love", author: "Colleen Hoover", image: { url: "https://covers.openlibrary.org/b/id/8743548-L.jpg" } },
  { title: "Haunting Adeline", author: "H.D. Carlton", image: { url: "https://covers.openlibrary.org/b/id/13259272-L.jpg" } },
  { title: "Twisted Love", author: "Ana Huang", image: { url: "https://covers.openlibrary.org/b/id/12803863-L.jpg" } },
  { title: "Twisted Games", author: "Ana Huang", image: { url: "https://covers.openlibrary.org/b/id/12803864-L.jpg" } },
  { title: "Twisted Hate", author: "Ana Huang", image: { url: "https://covers.openlibrary.org/b/id/12803865-L.jpg" } },
  { title: "Twisted Lies", author: "Ana Huang", image: { url: "https://covers.openlibrary.org/b/id/13557087-L.jpg" } },
  { title: "King of Wrath", author: "Ana Huang", image: { url: "https://covers.openlibrary.org/b/id/13897081-L.jpg" } },
  { title: "The Love Hypothesis", author: "Ali Hazelwood", image: { url: "https://covers.openlibrary.org/b/id/12349040-L.jpg" } },
  { title: "Love on the Brain", author: "Ali Hazelwood", image: { url: "https://covers.openlibrary.org/b/id/13104399-L.jpg" } },
  { title: "The Spanish Love Deception", author: "Elena Armas", image: { url: "https://covers.openlibrary.org/b/id/12349039-L.jpg" } },
  { title: "Icebreaker", author: "Hannah Grace", image: { url: "https://covers.openlibrary.org/b/id/13588072-L.jpg" } },
  { title: "Better Than the Movies", author: "Lynn Painter", image: { url: "https://covers.openlibrary.org/b/id/10521091-L.jpg" } },
  { title: "The Hating Game", author: "Sally Thorne", image: { url: "https://covers.openlibrary.org/b/id/8741441-L.jpg" } },
  { title: "Beach Read", author: "Emily Henry", image: { url: "https://covers.openlibrary.org/b/id/10308495-L.jpg" } },
  { title: "Book Lovers", author: "Emily Henry", image: { url: "https://covers.openlibrary.org/b/id/12992068-L.jpg" } },
  { title: "People We Meet on Vacation", author: "Emily Henry", image: { url: "https://covers.openlibrary.org/b/id/10521090-L.jpg" } },
  { title: "Happy Place", author: "Emily Henry", image: { url: "https://covers.openlibrary.org/b/id/13897082-L.jpg" } },
  { title: "Archer's Voice", author: "Mia Sheridan", image: { url: "https://covers.openlibrary.org/b/id/8743547-L.jpg" } },
  { title: "The Seven Husbands of Evelyn Hugo", author: "Taylor Jenkins Reid", image: { url: "https://covers.openlibrary.org/b/id/8749673-L.jpg" } },
  { title: "Daisy Jones and The Six", author: "Taylor Jenkins Reid", image: { url: "https://covers.openlibrary.org/b/id/8750832-L.jpg" } },
  { title: "Normal People", author: "Sally Rooney", image: { url: "https://covers.openlibrary.org/b/id/8750252-L.jpg" } },
  { title: "Punk 57", author: "Penelope Douglas", image: { url: "https://covers.openlibrary.org/b/id/8743550-L.jpg" } },
  { title: "Credence", author: "Penelope Douglas", image: { url: "https://covers.openlibrary.org/b/id/10308496-L.jpg" } },
  { title: "The Fine Print", author: "Lauren Asher", image: { url: "https://covers.openlibrary.org/b/id/12349038-L.jpg" } },
  { title: "Terms and Conditions", author: "Lauren Asher", image: { url: "https://covers.openlibrary.org/b/id/12803862-L.jpg" } },
];

module.exports = romanceCovers;